# Generated by Django 5.1.7 on 2025-04-18 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='analysisresult',
            old_name='created_at',
            new_name='analysis_timestamp',
        ),
        migrations.RemoveField(
            model_name='analysisresult',
            name='negative_sentiments',
        ),
        migrations.RemoveField(
            model_name='analysisresult',
            name='neutral_sentiments',
        ),
        migrations.RemoveField(
            model_name='analysisresult',
            name='positive_sentiments',
        ),
        migrations.AddField(
            model_name='analysisresult',
            name='negative_sentiment_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='analysisresult',
            name='neutral_sentiment_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='analysisresult',
            name='positive_sentiment_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='analysisresult',
            name='total_comments_analyzed',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='analysisresult',
            name='comments_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='analysisresult',
            name='upvotes',
            field=models.IntegerField(default=0),
        ),
    ]
