# Generated by Django 5.1.7 on 2025-04-18 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0002_rename_created_at_analysisresult_analysis_timestamp_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analysisresult',
            name='url',
            field=models.URLField(db_index=True),
        ),
    ]
